version: "3.7"
services:
  frontend:
    user: root
    build:
      context: .
    container_name: frontend
    ports:
      - "8080:80"
      - "3001:443"
    volumes:
      - ../telesystem:/app
      - ./.nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx


